server:
  port: 8081
spring:
  application:
    name: KDine
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/k_reviews?useSSL=false&serverTimezone=UTC
    username: root
    password: root123
  redis:
    host: 127.0.0.1
    port: 6379
#    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
    # 生产者发送消息到交换机 confirm 机制
    publisher-confirm-type: correlated
    # 生产者交换机到队列 确认回调
    publisher-returns: true
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.krrz: debug