---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by krrz.
--- DateTime: 2023/4/25 19:21
---
local voucherId = ARGV[1]
local userId=ARGV[2]
local orderId=ARGV[3]

local stockKey = 'KDine:seckill:stock:' .. voucherId
local orderKey = 'KDine:seckill:order:' .. voucherId

if(tonumber(redis.call('get',stockKey)) <= 0) then
    return 1
end

-- 判断用户是否下单
if(redis.call('sismember',orderKey,userId)==1) then
--    存在说明重复下单
    return 2
end


--扣库存
redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)
--redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0
